#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <kernel/system.h>
#include <kernel/keyboard.h>
#include <kernel/pci.h>

//Ports
#define PIO_IO_BASE_PORT 0x1F0
#define PIO_CONTROL_BASE_PORT 0x3F6
#define PIO_ALT_IO_BASE_PORT 0x170
#define PIO_ALT_CONTROL_BASE_PORT 0x376

//Registers
#define PIO_DATA_REGISTER PIO_IO_BASE_PORT + 0
#define PIO_ERROR_REGISTER PIO_IO_BASE_PORT + 1
#define PIO_FEATURES_REGISTER PIO_IO_BASE_PORT + 1
#define PIO_SECTOR_COUNT_REGISTER PIO_IO_BASE_PORT + 2
#define PIO_SECTOR_NUMBER_REGISTER PIO_IO_BASE_PORT + 3
#define PIO_LBA_LO PIO_IO_BASE_PORT + 3
#define PIO_CYLINDER_LOW_REGISTER PIO_IO_BASE_PORT + 4
#define PIO_LBA_MID PIO_IO_BASE_PORT + 4
#define PIO_CYLINDER_HIGH_REGISTER PIO_IO_BASE_PORT + 5
#define PIO_LBA_MID PIO_IO_BASE_PORT + 5
#define PIO_DRIVE_HEAD_REGISTER PIO_IO_BASE_PORT + 6
#define PIO_STATUS_REGISTER PIO_IO_BASE_PORT + 7
#define PIO_COMMAND_REGISTER PIO_IO_BASE_PORT + 7
#define PIO_ALT_STATUS_REGISTER PIO_CONTROL_BASE_PORT + 0
#define PIO_DEVICE_CONTROL_REGISTER PIO_CONTROL_BASE_PORT + 0
#define PIO_DRIVE_ADDRESS_REGISTER PIO_CONTROL_BASE_PORT + 1

// Secondary registers
#define PIO_SECONDARY_DATA_REGISTER PIO_ALT_IO_BASE_PORT + 0
#define PIO_SECONDARY_ERROR_REGISTER PIO_ALT_IO_BASE_PORT + 1
#define PIO_SECONDARY_FEATURES_REGISTER PIO_ALT_IO_BASE_PORT + 1
#define PIO_SECONDARY_SECTOR_COUNT_REGISTER PIO_ALT_IO_BASE_PORT + 2
#define PIO_SECONDARY_SECTOR_NUMBER_REGISTER PIO_ALT_IO_BASE_PORT + 3
#define PIO_SECONDARY_LBA_LO PIO_ALT_IO_BASE_PORT + 3
#define PIO_SECONDARY_CYLINDER_LOW_REGISTER PIO_ALT_IO_BASE_PORT + 4
#define PIO_SECONDARY_LBA_MID PIO_ALT_IO_BASE_PORT + 4
#define PIO_SECONDARY_CYLINDER_HIGH_REGISTER PIO_ALT_IO_BASE_PORT + 5
#define PIO_SECONDARY_LBA_MID PIO_ALT_IO_BASE_PORT + 5
#define PIO_SECONDARY_DRIVE_HEAD_REGISTER PIO_ALT_IO_BASE_PORT + 6
#define PIO_SECONDARY_STATUS_REGISTER PIO_ALT_IO_BASE_PORT + 7
#define PIO_SECONDARY_COMMAND_REGISTER PIO_ALT_IO_BASE_PORT + 7
#define PIO_SECONDARY_ALT_STATUS_REGISTER PIO_ALT_CONTROL_BASE_PORT + 0
#define PIO_SECONDARY_DEVICE_CONTROL_REGISTER PIO_ALT_CONTROL_BASE_PORT + 0
#define PIO_SECONDARY_DRIVE_ADDRESS_REGISTER PIO_ALT_CONTROL_BASE_PORT + 1

// If the bus is floating then no disks exist or forgot to flush the cache
bool floating_bus_check(char reg)
{
	uint16_t status = inb(reg);
	if (status == 0xFF)
		return true;
	else
		return false;
}
